use crate::{accounts::Accounts, block::Block};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::collections::VecDeque;

// 1 full network token = 100,000,000 base units (8 decimal places)
// 1 base unit = 0.00000001 network tokens
pub const DECIMALS: u64 = 100_000_000;

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub enum JobStatus {
    Pending,
        Processing,
            Completed,
            }

            #[derive(Clone, Debug, Serialize, Deserialize)]
            pub struct Job {
                pub id: String,
                    pub prompt: String,
                        pub status: JobStatus,
                        }

                        pub struct Chain {
                            pub blocks: Vec<Block>,
                                pub accounts: Accounts,
                                    pub job_queue: VecDeque<Job>,
                                    }

                                    impl Chain {
                                        pub fn new() -> Self {
                                                let genesis = Self::genesis_block();
                                                        Self {
                                                                    blocks: vec![genesis],
                                                                                accounts: Accounts::new(),
                                                                                            job_queue: VecDeque::new(),
                                                                                                    }
                                                                                                        }

                                                                                                            fn genesis_block() -> Block {
                                                                                                                    let timestamp = Utc::now().timestamp();
                                                                                                                            let mut hasher = Sha256::new();
                                                                                                                                    hasher.update(b"genesis");
                                                                                                                                            let hash = format!("{:x}", hasher.finalize());

                                                                                                                                                    Block {
                                                                                                                                                                index: 0,
                                                                                                                                                                            timestamp,
                                                                                                                                                                                        job_id: "genesis".into(),
                                                                                                                                                                                                    miner_address: "system".into(),
                                                                                                                                                                                                                tokens_used: 0,
                                                                                                                                                                                                                            reward_units: 0,
                                                                                                                                                                                                                                        previous_hash: String::new(),
                                                                                                                                                                                                                                                    block_hash: hash,
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                    pub fn last_hash(&self) -> String {
                                                                                                                                                                                                                                                                            self.blocks.last().unwrap().block_hash.clone()
                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                    pub fn next_index(&self) -> u64 {
                                                                                                                                                                                                                                                                                            self.blocks.len() as u64
                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                    pub fn add_job(&mut self, prompt: String) -> Job {
                                                                                                                                                                                                                                                                                                            let job = Job {
                                                                                                                                                                                                                                                                                                                        id: format!("job-{}", Utc::now().timestamp_nanos_opt().unwrap_or(0)),
                                                                                                                                                                                                                                                                                                                                    prompt,
                                                                                                                                                                                                                                                                                                                                                status: JobStatus::Pending,
                                                                                                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                                                                                                self.job_queue.push_back(job.clone());
                                                                                                                                                                                                                                                                                                                                                                        job
                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                pub fn fetch_next_job(&mut self) -> Option<Job> {
                                                                                                                                                                                                                                                                                                                                                                                        if let Some(job) = self.job_queue.iter_mut().find(|j| j.status == JobStatus::Pending) {
                                                                                                                                                                                                                                                                                                                                                                                                    job.status = JobStatus::Processing;
                                                                                                                                                                                                                                                                                                                                                                                                                return Some(job.clone());
                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                None
                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                        pub fn create_block(
                                                                                                                                                                                                                                                                                                                                                                                                                                                &mut self,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        job_id: String,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                miner_address: String,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        tokens_used: u64,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) -> Block {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 1 compute token used = 1 base unit (0.00000001 network tokens)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            let reward_units = tokens_used;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Credit miner account in base units
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.accounts.credit(&miner_address, reward_units);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Mark queued job as completed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if let Some(job) = self.job_queue.iter_mut().find(|j| j.id == job_id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        job.status = JobStatus::Completed;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let index = self.next_index();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let timestamp = Utc::now().timestamp();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        let previous_hash = self.last_hash();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let mut hasher = Sha256::new();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hasher.update(index.to_be_bytes());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                hasher.update(timestamp.to_be_bytes());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hasher.update(job_id.as_bytes());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                hasher.update(miner_address.as_bytes());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hasher.update(tokens_used.to_be_bytes());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                hasher.update(reward_units.to_be_bytes());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hasher.update(previous_hash.as_bytes());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let block_hash = format!("{:x}", hasher.finalize());

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Block {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    index,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                timestamp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            job_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        miner_address,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tokens_used,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                reward_units,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            previous_hash,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        block_hash,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }