use crate::{accounts::Accounts, block::Block};
use chrono::Utc;
use sha2::{Digest, Sha256};

pub struct Chain {
    pub blocks: Vec<Block>,
        pub accounts: Accounts,
        }

        impl Chain {
            pub fn new() -> Self {
                    let genesis = Self::genesis_block();
                            Self {
                                        blocks: vec![genesis],
                                                    accounts: Accounts::new(),
                                                            }
                                                                }

                                                                    fn genesis_block() -> Block {
                                                                            let timestamp = Utc::now().timestamp();
                                                                                    let mut hasher = Sha256::new();
                                                                                            hasher.update(b"genesis");
                                                                                                    let hash = format!("{:x}", hasher.finalize());

                                                                                                            Block {
                                                                                                                        index: 0,
                                                                                                                                    timestamp,
                                                                                                                                                job_id: "genesis".into(),
                                                                                                                                                            miner_address: "system".into(),
                                                                                                                                                                        tokens_used: 0,
                                                                                                                                                                                    reward_units: 0,
                                                                                                                                                                                                previous_hash: String::new(),
                                                                                                                                                                                                            block_hash: hash,
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                            pub fn last_hash(&self) -> String {
                                                                                                                                                                                                                                    self.blocks.last().unwrap().block_hash.clone()
                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                            pub fn next_index(&self) -> u64 {
                                                                                                                                                                                                                                                    self.blocks.len() as u64
                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                            pub fn create_block(
                                                                                                                                                                                                                                                                    &mut self,
                                                                                                                                                                                                                                                                            job_id: String,
                                                                                                                                                                                                                                                                                    miner_address: String,
                                                                                                                                                                                                                                                                                            tokens_used: u64,
                                                                                                                                                                                                                                                                                                ) -> Block {
                                                                                                                                                                                                                                                                                                        let reward_units = tokens_used; // 1:1 reward

                                                                                                                                                                                                                                                                                                                // credit miner
                                                                                                                                                                                                                                                                                                                        self.accounts.credit(&miner_address, reward_units);

                                                                                                                                                                                                                                                                                                                                let index = self.next_index();
                                                                                                                                                                                                                                                                                                                                        let timestamp = Utc::now().timestamp();
                                                                                                                                                                                                                                                                                                                                                let previous_hash = self.last_hash();

                                                                                                                                                                                                                                                                                                                                                        let mut hasher = Sha256::new();
                                                                                                                                                                                                                                                                                                                                                                hasher.update(index.to_be_bytes());
                                                                                                                                                                                                                                                                                                                                                                        hasher.update(timestamp.to_be_bytes());
                                                                                                                                                                                                                                                                                                                                                                                hasher.update(job_id.as_bytes());
                                                                                                                                                                                                                                                                                                                                                                                        hasher.update(miner_address.as_bytes());
                                                                                                                                                                                                                                                                                                                                                                                                hasher.update(tokens_used.to_be_bytes());
                                                                                                                                                                                                                                                                                                                                                                                                        hasher.update(reward_units.to_be_bytes());
                                                                                                                                                                                                                                                                                                                                                                                                                hasher.update(previous_hash.as_bytes());
                                                                                                                                                                                                                                                                                                                                                                                                                        let block_hash = format!("{:x}", hasher.finalize());

                                                                                                                                                                                                                                                                                                                                                                                                                                Block {
                                                                                                                                                                                                                                                                                                                                                                                                                                            index,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        timestamp,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    job_id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                miner_address,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            tokens_used,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reward_units,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    previous_hash,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                block_hash,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }